# 🧠 NumPy 极简速记笔记 (数据分析版)

> **学习原则**：不记函数名，记“超能力”。当 Pandas 变慢或处理纯数值逻辑时，请呼叫 NumPy。

---

## 🛠️ 第一类：造数 (像开工厂)
| 动作 | 函数 | 常用场景 |
| :--- | :--- | :--- |
| **等差数列** | `np.arange(0, 10, 2)` | 生成 0, 2, 4... 常用于循环或列编号 |
| **均匀切分** | `np.linspace(0, 1, 5)` | 生成坐标轴刻度 0, 0.25... 1.0 |
| **随机数** | `np.random.randn(3,3)` | 模拟实验数据、正态分布采样 |

---

## 🧩 第二类：变形 (像玩乐高)
| 动作 | 函数 | 常用场景 |
| :--- | :--- | :--- |
| **重塑形状** | `.reshape(3, 4)` | 把月销量列表变成“季度x月份”表格 |
| **自动变维** | `.reshape(4, -1)` | 只定行数，让电脑自动算还要几列 |

---

## ⚡ 第三类：逻辑与计算 (最强武器)
| 动作 | 函数 | 常用场景 |
| :--- | :--- | :--- |
| **CASE WHEN** | `np.where(条件, 是, 否)` | **必杀技！** 根据价格给千万行数据打“高端/低端”标签 |
| **多分支打标** | `np.select(条件组, 标签组)` | **进阶神技！** 处理 3 个以上档位，逻辑清晰极爽 |
| **数学平滑** | `np.log(arr)` | 处理长尾分布（如房价、销量），让数据更符合统计规律 |
| **多维聚合** | `arr.mean(axis=0)` | 压缩维度：比如在 3D 数据中只求某一层的平均值 |

---


---
## 💡 常用代码片段 (Code Snippet)
快速上手代码：


In [2]:
import numpy as np

arr = np.array([1,2,3,4,5,6])
print(arr.mean())
print(arr[arr > 3])

3.5
[4 5 6]


In [11]:
scores = np.array([
    [85, 92],  # 学生A
    [58, 45],  # 学生B
    [90, 88]   # 学生C
])

fail_scores = scores[scores < 60]
print(fail_scores)

print(scores.mean(axis=0).mean())

print(scores +2)

[58 45]
76.33333333333334
[[87 94]
 [60 47]
 [92 90]]


## NumPy 在数据分析中的核心场景

虽然 Pandas 是数据分析的主角，但 **NumPy 是它的“发动机”**。以下是 NumPy 最常用的三个“必杀技”：

1. **快速生成模拟数据/底表**：`arange` (等差数列), `linspace` (均分数列), `random` (随机数)。
2. **多维数组变维 (Reshape)**：这在机器学习和高级统计中非常重要。
3. **极速数值处理**：当 Pandas 的 `.apply()` 太慢时，直接用 NumPy 的底层函数。

---
### 技巧 1：生成序列与随机数
在做模拟分析时，我们经常需要生成一串连续的数字。

In [3]:
# 生成 0 到 10 的等差数列 (步长为 2)
even_nums = np.arange(0, 11, 2)
print("0到10的偶数:", even_nums)

# 在 0 到 1 之间均匀生成 5 个数 (常用于图表坐标轴)
uniform_nums = np.linspace(0, 1, 5)
print("0到1均分5份:", uniform_nums)

# 生成 3x3 的标准正态分布随机数 (平均值0, 标准差1)
random_matrix = np.random.randn(3, 3)
print("\n随机矩阵:\n", random_matrix)

0到10的偶数: [ 0  2  4  6  8 10]
0到1均分5份: [0.   0.25 0.5  0.75 1.  ]

随机矩阵:
 [[-0.11846468  1.73040504 -1.04628328]
 [-2.32106942  0.39863784  0.2000188 ]
 [-1.25385683 -0.63961035  0.0951041 ]]


### 技巧 2：变维与重构（Reshape）
**“把 12 个数拼成 3x4 的表格”**，这在处理图像或深度学习时是家常便饭。
在分析产品数据时，如果你有 3 年共 12 个月的月销量，你可以把它变成 `(3, 4)` 的矩阵。

In [4]:
# 1. 自动生成一个包含 12 个元素的数组
original_arr = np.arange(12)

# 2. 变换形状 (reshape 为 3行 4列)
# 注意: 形状的长宽之积必须等于原数组的总长度 (3*4=12)
reshaped_arr = original_arr.reshape(3, 4)
print("Reshape 后的 3x4 矩阵:\n", reshaped_arr)

# 3. 如果不知道某一边有多少列，可以写 -1 让 np 自动计算
auto_arr = original_arr.reshape(4, -1)
print("\n自动计算列数 (4x3):\n", auto_arr)

Reshape 后的 3x4 矩阵:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

自动计算列数 (4x3):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


### 技巧 3：极速数值运算与数学函数
在 Pandas 里面，你可能需要用 `.apply(np.log)` 才能对一整列取对数。
但在 NumPy 里，你可以 **一键** 对全数组所有元素做各种数学操作。

*   **`np.log()`** / **`np.exp()`**: 对数/指数，金融建模常用。
*   **`np.sqrt()`**: 平方根。
*   **`np.where()`**: 数组版的 `if-else` (非常像 SQL 的 `CASE WHEN`)。

In [6]:
# 示例：快速做决策打标 (np.where)
# 语法: np.where(条件, 符合则为, 不符合则为)
prices = np.array([5500, 6800, 4200, 7500, 3900])
labels = np.where(prices > 4000, "Premium", "Budget")

print("价格数据:", prices)
print("自动生成的标签:", labels)

# 计算数组的对数 (常用于平滑具有长尾分布的数据)
print("\n价格对数结果:", np.log(prices))

价格数据: [5500 6800 4200 7500 3900]
自动生成的标签: ['Premium' 'Premium' 'Premium' 'Premium' 'Budget']

价格对数结果: [8.61250337 8.82467789 8.3428398  8.9226583  8.26873183]


## 🚀 NumPy + Pandas 梦幻联动 (高级打标)

当你的业务逻辑变得复杂（比如需要分 3 档、4 档以上）时，嵌套的 `if` 或者 `np.where` 会让代码变得难以维护。

**`np.select`** 是处理这种“多分支打标”的最强武器，它的逻辑完美对应 SQL 的 `CASE WHEN`。

In [7]:
import pandas as pd

# 1. 模拟一个简单的电脑数据表
df_test = pd.DataFrame({
    '型号': ['A', 'B', 'C', 'D', 'E'],
    '价格': [12000, 7500, 5200, 3999, 8500]
})

# 2. 定义多个条件列表 (像是在写 SQL 的 WHEN)
conditions = [
    (df_test['价格'] >= 10000),  # 顶级档位
    (df_test['价格'] >= 6000),   # 中端主力
    (df_test['价格'] < 6000)    # 性价比之选
]

# 3. 定义对应的标签 (像是在写 SQL 的 THEN)
choices = ['顶级尊享', '中端主力', '入门级']

# 4. 一键完成多分支打标 (SQL's CASE WHEN 镜像函数)
df_test['定位'] = np.select(conditions, choices, default='待定')

print("多分支打标结果:\n", df_test)
print("\n--- 技巧回顾 ---")
print("np.where = 2个分支的开关")
print("np.select = 3个以上分支的指挥台")

多分支打标结果:
   型号     价格    定位
0  A  12000  顶级尊享
1  B   7500  中端主力
2  C   5200   入门级
3  D   3999   入门级
4  E   8500  中端主力

--- 技巧回顾 ---
np.where = 2个分支的开关
np.select = 3个以上分支的指挥台
